config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  get 'landing', to: 'cocktails#landing', as: :landing

  resources :cocktails, only: %i[index show new create destroy] do
    resources :doses, only: [:create]
    # resources :ingredients, only: [:create]
  end
  resources :doses, only: %i[destroy edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: %i[show destroy]

  def index
    @cocktail = Cocktail.new
    if params[:name]
      @cocktails = Cocktail.where("name LIKE '%#{params[:name]}%'")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end


  def landing
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id].to_i)
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_dose, only: %i[destroy]

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to root_path()
    else
      redirect_to root_path()
    end
  end

  def edit
    @dose = Dose.find(params[:id])
  end

  def destroy
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def find_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= form_for @cocktail, html: { class: 'new-form-content' } do |f| %>
  <div class="form-group form-class justify-content-center">
    <%= f.text_field :name, class:"form-control input", placeholder: "Cocktail's name" %>
    <%= f.file_field :photo, class:"upload-button justify-content-center" %>
    <%= f.submit class:"btn btn-primary submit" %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Here is "name of bar"</h1>
    <%= link_to new_cocktail_path do %>
    <div class="btn btn-primary btn-lg">Add a Cocktail</div>
    <%= link_to("CRAZY LANDING PAGE", landing_path(), :class => "btn btn-danger" )%>

    <% end %>
  </div>
</div>


<br>
<br>

<div class="wrapper">
  <div class="banner text-center justify-content-center" style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1WdWzueJ9VMdvapHQ3d-gKl5qkqukpIHHCf95UJxpxKZrqBdB);">
      <p>
        <span id="banner-typed-text" style="color: white !important"></span>
      </p>
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#new_cocktail_modal">
        <i class="fas fa-plus"></i> Cocktail
      </button>
  </div>
  <div class="modal fade" id="new_cocktail_modal" tabindex="-1" role="dialog" aria-labelledby="new_cocktail_modal_title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add your favourite cocktail</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_for @cocktail, html: { class: 'new-form-content' } do |f| %>
          <div class="modal-body">
            <div class="form-group form-class justify-content-center">
              <%= f.text_field :name, class:"form-control input", placeholder: "Cocktail's name" %>
              <%= f.file_field :photo, class:"upload-button justify-content-center" %>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.submit class:"btn btn-primary submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <h1 class="text-center" id="index-title">All Cocktails</h1>
    <%= form_tag("#{cocktails_path}#index-title", method: :get, class:"form-inline justify-content-center text-center") do %>
      <%= text_field_tag(:name, params[:name], placeholder: "Search", class:"form-control") %>
      <%= submit_tag("Search", name: nil, class:"btn btn-primary") %>
    <% end %>
    <% if Cocktail.count != @cocktails.count %>
      <% if @cocktails.count.zero? %>
        <p>We haven't found any cocktails matching your search.</p>
      <% elsif @cocktails.count == 1 %>
        <p>We found <%= @cocktails.count %> cocktail.</p>
      <% else %>
        <p>We found <%= @cocktails.count %> cocktails.</p>
      <% end %>
    <% end %>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card">

            <div class="cocktail-name">
              <%= link_to cocktail.name, cocktail_path(cocktail), class:"cocktail-list-link" %>
              <%= link_to "#{cocktail_path(cocktail)}#index-title", method: :delete do %>
                <i class="fas fa-trash-alt trash-link"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<br>
<br>
<br>
<br>


</div>
<h1> Other way to show all my COCKTAILS </h1>

<div class="card-product">

  <% @cocktails.each do |cocktail| %>
    <div class="card-product-infos">
      <div class="card-product-info">
<!--         <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
 -->
          <%= image_tag cocktail.photo, height: 200, width: 200%>
          <div class="card-product-infos">
          <h2> <%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          <i class="fas fa-trash-alt trash-link"></i>
        </div>
      </div>
    </div>
  <% end %>
</div>





<br>
<br>
<br>
<br>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon <i class="fas fa-heart"></i>
  </div>
</div>

app/views/cocktails/landing.html.erb
<div class="ultimate-wrapper">


  <div id="wraper">



    <p>
      <span id="banner-typed-text" style="color: black !important"></span>
    </p>


    <div class="eyes">
      <div class="eye">
        <div class="ball"></div>
      </div>

      <div class="eye">
        <div class="ball"></div>
      </div>
    </div>



    <div class="container-button">

      <div class="button1 flex-item">
        <%= link_to cocktails_path do %>

          <button type="button" class="btn btn-danger button-landing sticky-bottom">CLICK HERE TO ORDER</button>

        <% end %>

      </div>

      <div class="button2 flex-item" >
        <button id="sweet-alert-dem" class="btn btn-primary">Click me!</button>
      </div>


    </div>
    <br>
    <br>

    <p class="typed-text">
      <span id="banner-typed-text-2" style="color: orange"></span>
    </p>


  </div>



  <div class="middle">
    <a class="btn azerty" href="">
      <i class="fab fa-facebook-f"></i>
    </a>
    <a class="btn azerty" href="">
      <i class="fab fa-twitter"></i>
    </a>
    <a class="btn azerty" href="">
      <i class="fab fa-instagram"></i>
    </a>
    <a class="btn azerty" href="">
      <i class="fab fa-google-plus"></i>
    </a>
  </div>




</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<canvas id="canvas"></canvas>
<canvas id="sCanvas"></canvas>

app/views/cocktails/new.html.erb
<div class="wrapper text-center new-wrapper">
  <div class="container text-center new-form">
    <h1>Add a new Cocktail</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="wrapper">
  <div class="container text-center">
    <div class="show-page-image">
      <h2><%= @cocktail.name %></h2>
    </div>
    <div class="row">
      <% @cocktail.doses.each do |dose| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
          <div class="avatar" style="background: rgb( <%= rand(0..200) %>, <%= rand(0..200) %>, <%= rand(0..200) %> );">
            <p><%= dose.ingredient.name %></p>
            <%= link_to dose_path(dose), method: :delete do %>
              <i class="fas fa-trash-alt delete-avatar"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>



    <div class="row">
      <div class="col-xs-12 col-md-6">
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <div class="form-group">
            <%= f.input :description, input_html: { class: 'form-description', placeholder: "Description..." }, label: false, required: true %>
            <%= f.association :ingredient, collection: Ingredient.all.sort_by { |ingredient| ingredient.name.downcase }, label: false, include_blank: "Ingredient", input_html: { class: 'form-dropdown' }, required: true %>
            <%= f.submit class:"btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div class="wrap-button">
        <div class="col-xs-12 col-md-6">
          <%= simple_form_for [@cocktail] do |f| %>
            <div class="form-group">
              <%= f.submit class:"btn btn-primary" %>
            </div>
          <% end %>
          <%= link_to("HOME PAGE", root_path(), :class => "btn btn-success" )%>
          <br>
          <br>
          <%= link_to("CRAZY LANDING PAGE", landing_path(), :class => "btn btn-danger" )%>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [cocktail, dose] do |f| %>
  <div class="form-group">
    <%= f.input :description, class:"form-control" %>
    <%= f.association :ingredient, class:"form-control" %>
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/doses/edit.html.erb
<div class="container">
  <%= simple_form_for @dose do |f| %>
    <div class="form-group">
      <%= f.input :description, class:"form-control" %>
      <%= f.association :ingredient, class:"form-control" %>
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/doses/new.html.erb
<div class="wrapper">
  <div class="container">
      <%= render 'form', cocktail: @cocktail, dose: @dose %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>

    <meta charset="utf-8">
    <link rel="stylesheet" href="style.css">
    <title></title>



    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <div class="navbar-wagon-left">
        <%= link_to cocktails_path, class:"navbar-wagon-link" do %>
          <i class="fas fa-home"></i>
        <% end %>
      </div>
    </div>

<!--   <div class="eyes">
    <div class="eye">
      <div class="ball"></div>
    </div>

    <div class="eye">
      <div class="ball"></div>
    </div>
  </div>

<br>
<br>
<br>
<br>
<br>
<p>
  <span id="banner-typed-text"></span>
</p> -->

<!--
<script>
  var balls = document.getElementsByClassName("ball");
  document.onmousemove = function(){
    var x = event.clientX * 100 / window.innerWidth + "%";
    var y = event.clientY * 100 / window.innerHeight + "%";
    //event.clientX => get the horizontal coordinate of the mouse
    //event.clientY => get the Vertical coordinate of the mouse
    //window.innerWidth => get the browser width
    //window.innerHeight => get the browser height

    for(var i=0;i<2;i++){
      balls[i].style.left = x;
      balls[i].style.top = y;
      balls[i].style.transform = "translate(-"+x+",-"+y+")";
    }
  }

</script>
 -->
<!-- -->
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>